id=com.xtjm.fusionstatusbar
name=状态栏融合图标
version=@VERSION_NAME@
versionCode=@VERSION_CODE@
author=xtjm
description=支持融合图标、双排状态栏、自定义时间与天气，以及自由选位的双行温度、功率电流和网速。
minApiVersion=102
targetApiVersion=102
staticScope=true
